## Preprocessing

In [2]:
! pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.9.1-cp39-cp39-win_amd64.whl (444.0 MB)
Requirement already satisfied: six>=1.12.0 in c:\users\dskan\anaconda3\lib\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\dskan\anaconda3\lib\site-packages (from tensorflow) (3.10.0.2)
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.26.0-cp39-cp39-win_amd64.whl (1.5 MB)
Collecting tensorboard<2.10,>=2.9
  Downloading tensorboard-2.9.1-py3-none-any.whl (5.8 MB)
Collecting flatbuffers<2,>=1.12
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: setuptools in c:\users\dskan\anaconda3\lib\site-packages (from tensorflow) (58.0.4)
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\dskan\anaconda3\lib\site-packages (from tensorflow) (1.12.1)
Collecting gast<=0.4.0,>=0.2.1
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Collecting absl-py>=1.0.0
  Downloading absl_py-1.1.0-py3-none-any.whl (123 kB)
Collecting google-pasta>=0.1.1
  Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Collecting libclang>=13.0.0
  Downloading libclang-14.0.1-py2.py3-none-win_amd64.whl (14.2 MB)
Collecting keras-preprocessing>=1.1.1
  Downloading Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Collecting opt-einsum>=2.3.2
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting grpcio<2.0,>=1.24.3
  Downloading grpcio-1.46.3-cp39-cp39-win_amd64.whl (3.5 MB)
Collecting tensorflow-estimator<2.10.0,>=2.9.0rc0
  Downloading tensorflow_estimator-2.9.0-py2.py3-none-any.whl (438 kB)
Requirement already satisfied: h5py>=2.9.0 in c:\users\dskan\anaconda3\lib\site-packages (from tensorflow) (3.2.1)
Requirement already satisfied: packaging in c:\users\dskan\anaconda3\lib\site-packages (from tensorflow) (21.0)
Collecting termcolor>=1.1.0
  Downloading termcolor-1.1.0.tar.gz (3.9 kB)
Collecting keras<2.10.0,>=2.9.0rc0
  Downloading keras-2.9.0-py2.py3-none-any.whl (1.6 MB)
Collecting protobuf<3.20,>=3.9.2
  Downloading protobuf-3.19.4-cp39-cp39-win_amd64.whl (895 kB)
Requirement already satisfied: numpy>=1.20 in c:\users\dskan\anaconda3\lib\site-packages (from tensorflow) (1.20.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\dskan\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.37.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\dskan\anaconda3\lib\site-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.26.0)
Collecting markdown>=2.6.8
  Downloading Markdown-3.3.7-py3-none-any.whl (97 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\dskan\anaconda3\lib\site-packages (from tensorboard<2.10,>=2.9->tensorflow) (2.0.2)
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.7.0-py2.py3-none-any.whl (160 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Downloading tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.8-py3-none-any.whl (39 kB)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: importlib-metadata>=4.4 in c:\users\dskan\anaconda3\lib\site-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (4.8.1)
Requirement already satisfied: zipp>=0.5 in c:\users\dskan\anaconda3\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow) (3.6.0)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dskan\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\dskan\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dskan\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\dskan\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow) (1.26.7)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.0-py3-none-any.whl (151 kB)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\dskan\anaconda3\lib\site-packages (from packaging->tensorflow) (3.0.4)
Building wheels for collected packages: termcolor
  Building wheel for termcolor (setup.py): started
  Building wheel for termcolor (setup.py): finished with status 'done'
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4847 sha256=eb2d922877ad3a4e70514204fe2ea2995acdd6728365f6b01c08369c60f08601
  Stored in directory: c:\users\dskan\appdata\local\pip\cache\wheels\b6\0d\90\0d1bbd99855f99cb2f6c2e5ff96f8023fad8ec367695f7d72d
Successfully built termcolor
Installing collected packages: pyasn1, rsa, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, google-auth, tensorboard-plugin-wit, tensorboard-data-server, protobuf, markdown, grpcio, google-auth-oauthlib, absl-py, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard, opt-einsum, libclang, keras-preprocessing, keras, google-pasta, gast, flatbuffers, astunparse, tensorflow
Successfully installed absl-py-1.1.0 astunparse-1.6.3 cachetools-5.2.0 flatbuffers-1.12 gast-0.4.0 google-auth-2.7.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.46.3 keras-2.9.0 keras-preprocessing-1.1.2 libclang-14.0.1 markdown-3.3.7 oauthlib-3.2.0 opt-einsum-3.3.0 protobuf-3.19.4 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.1 rsa-4.8 tensorboard-2.9.1 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-2.9.1 tensorflow-estimator-2.9.0 tensorflow-io-gcs-filesystem-0.26.0 termcolor-1.1.0

In [3]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("../Resources/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
app_df = application_df.drop(['EIN', 'NAME'], 1)

C:\Users\dskan\AppData\Local\Temp/ipykernel_4920/4290258176.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  app_df = application_df.drop(['EIN', 'NAME'], 1)

In [5]:
app_df.head(5)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [6]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
app_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
app_counts = app_df['APPLICATION_TYPE'].value_counts()
print(app_counts)

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
app_types_to_replace = list(app_counts[app_counts < 500].index)
# Replace in dataframe
for app in app_types_to_replace:
    app_df['APPLICATION_TYPE'] = app_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
app_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [10]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_counts = app_df["CLASSIFICATION"].value_counts()
print(class_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [11]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
class_to_replace = list(class_counts[class_counts < 1000].index)
# Replace in dataframe
for cls in class_to_replace:
    app_df['CLASSIFICATION'] = app_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
app_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
app_dummies_df = pd.get_dummies(app_df)
app_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [14]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = app_dummies_df.drop(["IS_SUCCESSFUL"], axis='columns').values
y = app_dummies_df["IS_SUCCESSFUL"].values
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [26]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_features  = len(X_train[0])
layer_one_nodes = 50
layer_two_nodes = 20
layer_three_nodes = 10
nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=layer_one_nodes, input_dim=number_input_features, activation = 'relu'))

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=layer_two_nodes, input_dim=layer_one_nodes, activation = 'relu'))

# Output layer
#  YOUR CODE GOES HERE
nn.add(tf.keras.layers.Dense(units=layer_three_nodes, input_dim=layer_two_nodes, activation = 'relu'))

nn.add(tf.keras.layers.Dense(units=1, input_dim=layer_three_nodes, activation="sigmoid"))
# Check the structure of the model
nn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_10 (Dense)            (None, 50)                2200

 dense_11 (Dense)            (None, 20)                1020

 dense_12 (Dense)            (None, 10)                210

 dense_13 (Dense)            (None, 1)                 11

=================================================================
Total params: 3,441
Trainable params: 3,441
Non-trainable params: 0
_________________________________________________________________

In [27]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics="accuracy")

In [28]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=150)

Epoch 1/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5777 - accuracy: 0.7140
Epoch 2/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5582 - accuracy: 0.7272
Epoch 3/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5549 - accuracy: 0.7284
Epoch 4/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5527 - accuracy: 0.7290
Epoch 5/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5514 - accuracy: 0.7321
Epoch 6/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5512 - accuracy: 0.7308
Epoch 7/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5502 - accuracy: 0.7310
Epoch 8/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7328
Epoch 9/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5484 - accuracy: 0.7331
Epoch 10/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5483 - accuracy: 0.7316
Epoch 11/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5477 - accuracy: 0.7329
Epoch 12/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5472 - accuracy: 0.7339
Epoch 13/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5471 - accuracy: 0.7327
Epoch 14/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5470 - accuracy: 0.7345
Epoch 15/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5464 - accuracy: 0.7347
Epoch 16/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5461 - accuracy: 0.7347
Epoch 17/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5459 - accuracy: 0.7348
Epoch 18/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7343
Epoch 19/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5452 - accuracy: 0.7347
Epoch 20/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5453 - accuracy: 0.7352
Epoch 21/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5451 - accuracy: 0.7346
Epoch 22/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5447 - accuracy: 0.7355
Epoch 23/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7339
Epoch 24/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5441 - accuracy: 0.7351
Epoch 25/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5439 - accuracy: 0.7357
Epoch 26/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7353
Epoch 27/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7348
Epoch 28/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7353
Epoch 29/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5437 - accuracy: 0.7355
Epoch 30/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5432 - accuracy: 0.7360
Epoch 31/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7352
Epoch 32/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5430 - accuracy: 0.7353
Epoch 33/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7358
Epoch 34/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5429 - accuracy: 0.7358
Epoch 35/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5426 - accuracy: 0.7367
Epoch 36/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7361
Epoch 37/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7363
Epoch 38/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5418 - accuracy: 0.7362
Epoch 39/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7364
Epoch 40/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7371
Epoch 41/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7364
Epoch 42/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7350
Epoch 43/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5416 - accuracy: 0.7360
Epoch 44/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7369
Epoch 45/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7368
Epoch 46/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5413 - accuracy: 0.7365
Epoch 47/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5414 - accuracy: 0.7356
Epoch 48/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7374
Epoch 49/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7360
Epoch 50/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7364
Epoch 51/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7361
Epoch 52/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7373
Epoch 53/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7369
Epoch 54/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5405 - accuracy: 0.7371
Epoch 55/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7367
Epoch 56/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5403 - accuracy: 0.7370
Epoch 57/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7356
Epoch 58/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7369
Epoch 59/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7364
Epoch 60/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7367
Epoch 61/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7362
Epoch 62/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7370
Epoch 63/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7371
Epoch 64/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7371
Epoch 65/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5399 - accuracy: 0.7361
Epoch 66/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7363
Epoch 67/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7368
Epoch 68/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7369
Epoch 69/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5397 - accuracy: 0.7373
Epoch 70/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5395 - accuracy: 0.7368
Epoch 71/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7367
Epoch 72/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7374
Epoch 73/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7379
Epoch 74/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5389 - accuracy: 0.7374
Epoch 75/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7366
Epoch 76/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7376
Epoch 77/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5392 - accuracy: 0.7372
Epoch 78/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7381
Epoch 79/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7375
Epoch 80/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7369
Epoch 81/150

804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7370
Epoch 82/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7371
Epoch 83/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7371
Epoch 84/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7373
Epoch 85/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 86/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7385
Epoch 87/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7378
Epoch 88/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7381
Epoch 89/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7384
Epoch 90/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7371
Epoch 91/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7378
Epoch 92/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7380
Epoch 93/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5380 - accuracy: 0.7372
Epoch 94/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7381
Epoch 95/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5373 - accuracy: 0.7380
Epoch 96/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7376
Epoch 97/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7383
Epoch 98/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7381
Epoch 99/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7381
Epoch 100/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5383 - accuracy: 0.7381
Epoch 101/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5378 - accuracy: 0.7379
Epoch 102/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7390
Epoch 103/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 104/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7387
Epoch 105/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5376 - accuracy: 0.7383
Epoch 106/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7383
Epoch 107/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5378 - accuracy: 0.7383
Epoch 108/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5373 - accuracy: 0.7385
Epoch 109/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7386
Epoch 110/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5373 - accuracy: 0.7380
Epoch 111/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7383
Epoch 112/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7383
Epoch 113/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7392
Epoch 114/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7386
Epoch 115/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5371 - accuracy: 0.7387
Epoch 116/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7393
Epoch 117/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7383
Epoch 118/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7385
Epoch 119/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7378
Epoch 120/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7384
Epoch 121/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5369 - accuracy: 0.7383
Epoch 122/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5373 - accuracy: 0.7383
Epoch 123/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7386
Epoch 124/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7396
Epoch 125/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7383
Epoch 126/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7383
Epoch 127/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7385
Epoch 128/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7399
Epoch 129/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7393
Epoch 130/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7393
Epoch 131/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7395
Epoch 132/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7382
Epoch 133/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5365 - accuracy: 0.7390
Epoch 134/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7390
Epoch 135/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7386
Epoch 136/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7390
Epoch 137/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7390
Epoch 138/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7388
Epoch 139/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7387
Epoch 140/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7389
Epoch 141/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5360 - accuracy: 0.7383
Epoch 142/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7385
Epoch 143/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7384
Epoch 144/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5360 - accuracy: 0.7388
Epoch 145/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7385
Epoch 146/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5364 - accuracy: 0.7390
Epoch 147/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7379
Epoch 148/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7394
Epoch 149/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5361 - accuracy: 0.7390
Epoch 150/150
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7385

In [29]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5734 - accuracy: 0.7334 - 319ms/epoch - 1ms/step
Loss: 0.5734348297119141, Accuracy: 0.7334110736846924

In [30]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("alphabetcharity.hd5")

INFO:tensorflow:Assets written to: alphabetcharity.hd5\assets